import fs from 'node:fs';
import path from 'node:path';
import { escapeHtml } from './html.mjs';

const FORMATS = [['avif', 'image/avif'], ['webp', 'image/webp']];

// Reads assets/photos/index.json (generated by `npm run photos`). No file means no photos yet.
export function loadPhotos(rootDir) {
  const file = path.join(rootDir, 'assets', 'photos', 'index.json');
  return fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : [];
}

export const photoForSlot = (photos, slot) => photos.find((photo) => photo.slots.includes(slot));
export const galleryPhotos = (photos) => photos.filter((photo) => photo.gallery);

const srcset = (photo, format) => photo.widths.map((width) => `/images/photos/${photo.name}-${width}.${format} ${width}w`).join(', ');

// The image used as the plain <img src> (and in the lightbox): the largest generated size up to maxWidth.
export function pickWidth(photo, maxWidth) {
  return [...photo.widths].reverse().find((width) => width <= maxWidth) || photo.widths[0];
}

// Parses key=value, key="value" and bare flags from a directive like: slot=hero class="a b" priority
function parseAttributes(text) {
  const attributes = {};
  for (const match of text.matchAll(/([\w-]+)(?:=(?:"([^"]*)"|(\S+)))?/g)) attributes[match[1]] = match[2] ?? match[3] ?? true;
  return attributes;
}

export function renderPicture(photo, { sizes = '100vw', className = '', priority = false, alt, decorative = false } = {}) {
  const fallbackWidth = pickWidth(photo, 800);
  const height = Math.round((photo.height / photo.width) * fallbackWidth);
  const altText = decorative ? '' : escapeHtml(alt ?? photo.alt);
  const sources = FORMATS.map(([format, type]) => `<source type="${type}" srcset="${srcset(photo, format)}" sizes="${escapeHtml(sizes)}" />`).join('');
  const loading = priority ? 'fetchpriority="high" decoding="async"' : 'loading="lazy" decoding="async"';

  return `<picture>${sources}<img src="/images/photos/${photo.name}-${fallbackWidth}.webp" width="${fallbackWidth}" height="${height}" alt="${altText}"${className ? ` class="${escapeHtml(className)}"` : ''} ${loading} /></picture>`;
}

function renderFallback(attributes) {
  const src = attributes.fallback;
  if (!src) return '';
  const alt = attributes['fallback-alt'] === undefined ? '' : escapeHtml(attributes['fallback-alt']);
  return `<img src="${escapeHtml(src)}" alt="${alt}"${attributes.class ? ` class="${escapeHtml(attributes.class)}"` : ''} loading="lazy" decoding="async" />`;
}

function renderGallery(photos) {
  const items = galleryPhotos(photos);
  const figures = items.map((photo, index) => {
    const wide = index % 5 === 0;
    const full = pickWidth(photo, 1600);
    return `<li class="gallery-item${wide ? ' gallery-item--wide' : ''}">
            <button type="button" class="gallery-open" data-gallery-open data-index="${index}" data-full="/images/photos/${photo.name}-${full}.webp" data-alt="${escapeHtml(photo.alt)}" aria-label="Enlarge photo: ${escapeHtml(photo.alt)}">
              ${renderPicture(photo, { sizes: wide ? '(min-width: 768px) 66vw, 100vw' : '(min-width: 768px) 33vw, 100vw', className: 'gallery-image' })}
              ${photo.caption ? `<span class="gallery-caption">${escapeHtml(photo.caption)}</span>` : ''}
            </button>
          </li>`;
  });

  return `<ul class="gallery-grid">
          ${figures.join('\n          ')}
        </ul>
        <dialog id="lightbox" class="lightbox" aria-label="Photo viewer">
          <figure class="lightbox__figure">
            <img id="lightbox-image" class="lightbox__image" src="data:image/gif;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=" alt="Enlarged photo" />
            <figcaption id="lightbox-caption" class="lightbox__caption"></figcaption>
          </figure>
          <button type="button" class="lightbox__button lightbox__prev" data-lightbox-prev aria-label="Previous photo">&#8592;</button>
          <button type="button" class="lightbox__button lightbox__next" data-lightbox-next aria-label="Next photo">&#8594;</button>
          <button type="button" class="lightbox__button lightbox__close" data-lightbox-close aria-label="Close photo viewer">&times;</button>
          <p class="sr-only" role="status" aria-live="polite" id="lightbox-status"></p>
        </dialog>`;
}

// Conditionals: <!-- @if photo:hero --> ... <!-- @else --> ... <!-- @endif -->  (also "photos" for the gallery).
function applyConditionals(content, photos) {
  const pattern = /<!--\s*@if\s+(photos|photo:[\w-]+)\s*-->([\s\S]*?)(?:<!--\s*@else\s*-->([\s\S]*?))?<!--\s*@endif\s*-->/g;

  return content.replace(pattern, (match, condition, whenTrue, whenFalse = '') => {
    const ok = condition === 'photos' ? galleryPhotos(photos).length > 0 : Boolean(photoForSlot(photos, condition.slice(6)));
    return ok ? whenTrue : whenFalse;
  });
}

// Replaces <!-- @photo ... --> and <!-- @gallery --> directives with generated HTML.
export function applyPhotoDirectives(content, photos) {
  return applyConditionals(content, photos)
    .replace(/<!--\s*@gallery\s*-->/g, () => renderGallery(photos))
    .replace(/<!--\s*@photo\s+([^>]*?)-->/g, (match, rawAttributes) => {
      const attributes = parseAttributes(rawAttributes);
      const photo = attributes.slot ? photoForSlot(photos, attributes.slot) : undefined;

      if (!photo) return renderFallback(attributes);
      return renderPicture(photo, {
        sizes: attributes.sizes || '100vw',
        className: attributes.class || '',
        priority: Boolean(attributes.priority),
        decorative: Boolean(attributes.decorative),
      });
    });
}

// <link rel="preload"> for the main image of a page (front matter "preload: hero"), when that photo exists.
export function preloadTag(photos, slot) {
  const photo = slot ? photoForSlot(photos, slot) : undefined;
  if (!photo) return '';
  return `<link rel="preload" as="image" type="image/avif" imagesrcset="${srcset(photo, 'avif')}" imagesizes="(min-width: 1024px) 50vw, 100vw" fetchpriority="high" />`;
}
